# This is a basic workflow to help you get started with Actions

 name: Releases

 # Controls when the workflow will run
 on:
   # Triggers the workflow on push or pull request events but only for the develop branch
   push:
     branches:
       - 'release/**'

   # Allows you to run this workflow manually from the Actions tab
   workflow_dispatch:

 # A workflow run is made up of one or more jobs that can run sequentially or in parallel
 jobs:
   # This workflow contains a single job called "build"
   build:
     # The type of runner that the job will run on
     runs-on: self-hosted

     # Steps represent a sequence of tasks that will be executed as part of the job
     steps:
       # Verify CI/CD node is online
       - name: Checking Machine is Available
         uses: sazid/zeuz-actions-check-node-availability@v1.1
         id: node_id
         with:
           zeuz_server_host: ${{ secrets.ZEUZ_SERVER_HOST }}
           zeuz_api_key: ${{ secrets.X_API_KEY }}
           zeuz_team_id: 2
           zeuz_project_id: PROJ-17
           node_id: ci_cd.*

       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
       - uses: actions/checkout@v2

       # Runs a set of commands using the runners shell
       - name: Run package scripts (Generates docs and full product .zip)
         run: | 
           cd package && npm install && CI=true npm start 

       - name: Archive production artifacts
         uses: actions/upload-artifact@v3
         with:
           name: release-zips
           path: package/**.zip

      # Upload & Replace Artifact into zeuz test case
       - name: Upload & Replace Build Artifact
         uses: sazid/zeuz-actions-upload-attachment@v1.0
         with:
           zeuz_server_host: ${{ secrets.ZEUZ_SERVER_HOST }}
           zeuz_api_key: ${{ secrets.X_API_KEY }}
           zeuz_attachment_type: ${{ vars.ZEUZ_ATTACHMENT_TYPE }}
           zeuz_attachment_item_id: ${{ vars.ZEUZ_ATTACHMENT_ITEM_ID }}
           zeuz_attachment_path: package/**.zip
           zeuz_attachment_replace: true

       # Runs a single set using the Preset API
       - name: Run Present API
         uses: sazid/zeuz-actions-deploy-preset@v1.0
         with:
           zeuz_preset_webhook: ${{ secrets.ZEUZ_PRESET_WEBHOOK }}
           zeuz_api_key: ${{ secrets.X_API_KEY }}
           zeuz_node_id: ${{ steps.node_id.outputs.node_id }}
           zeuz_objective: ${{ vars.ZEUZ_OBJECTIVE }}
           zeuz_version: ${{ vars.ZEUZ_VERSION }}
           zeuz_runtime_parameters: ${{ vars.ZEUZ_RUNTIME_PARAMETERS }}