# This is a basic workflow to help you get started with Actions

name: Test CI/CD

# Controls when the workflow will run
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Creating a dummy file
        run: echo "Hello World" >> test.txt

      - name: Step 1 - Checking Machine is Available
        uses: sazid/zeuz-actions-check-node-availability@v1.1
        with:
          zeuz_server_host: ${{ secrets.ZEUZ_SERVER_HOST }}
          zeuz_api_key: ${{ secrets.X_API_KEY }}
          zeuz_team_id: 2
          zeuz_project_id: PROJ-17
          node_id: faroque_backup

      - name: Step 2 - Upload & Replace Build Artifact
        uses: sazid/zeuz-actions-upload-attachment@v1.0
        with:
          zeuz_server_host: ${{ secrets.ZEUZ_SERVER_HOST }}
          zeuz_api_key: ${{ secrets.X_API_KEY }}
          zeuz_attachment_type: ${{ vars.ZEUZ_ATTACHMENT_TYPE }}
          zeuz_attachment_item_id: ${{ vars.ZEUZ_ATTACHMENT_ITEM_ID }}
          zeuz_attachment_path: test.txt
          zeuz_attachment_replace: true