# This is a basic workflow to help you get started with Actions

name: Test App Version

# Controls when the workflow will run
on:
  push:
    branches:
      - 'main'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout Github workspace
        uses: actions/checkout@v2

      - name: Collect Version Number
        id: getVersion
        run: cd app && cat pubspec.yaml | grep -o 'version:[^:+$]*' | head -1

      - name: Collecting Commit Details
        id: vars
        shell: bash
        run: |
          echo "hash=$(git rev-parse --short HEAD)" >>$GITHUB_OUTPUT
          echo "obj=$(git log -1 --format='%an'): hash: $(git log -1 --format='%an')" >>$GITHUB_OUTPUT

      - name: Output
        run: |
          echo "Obj: ${{ steps.vars.outputs.obj }}"

 


