# This is a basic workflow to help you get started with Actions

name: Test App Version

# Controls when the workflow will run
on:
  push:
    branches:
      - 'main'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - id: read-version
        uses: NiklasLehnfeld/flutter-version-number-action@main
        with:
          file-path: /home/runner/work/capture_by_curate/capture_by_curate/app/pubspec.yaml

      - name: Output flutter version
        run: echo 'version_number:' ${{ steps.read-version.outputs.version-number }}


      - name: Collecting Commit Details
        id: vars
        shell: bash
        run: |
          echo "author=$(git log -1 --format='%an')" >>$GITHUB_OUTPUT
          echo "obj=$(git log -1 --format='%an'): version_number: ${{ steps.read-version.outputs.version-number }}" >>$GITHUB_OUTPUT

 


